// Generated by Xata Codegen 0.29.5. Please do not edit.
import { buildClient } from "@xata.io/client";
import type {
  BaseClientOptions,
  SchemaInference,
  XataRecord,
} from "@xata.io/client";

const tables = [
  {
    name: "traducciones",
    columns: [
      { name: "TITULO", type: "string" },
      { name: "PAIS", type: "string" },
      { name: "VIDEOS", type: "string" },
      { name: "IDIOMA", type: "string" },
      { name: "CONTRATADOS", type: "int" },
      { name: "ORIGINALES", type: "string" },
      { name: "TRADUCIDOS", type: "string" },
      { name: "TRADUCCION", type: "string" },
      { name: "FICHAS", type: "string" },
      { name: "COMENTARIOS", type: "string" },
    ],
  },
] as const;

export type SchemaTables = typeof tables;
export type InferredTypes = SchemaInference<SchemaTables>;

export type Traducciones = InferredTypes["traducciones"];
export type TraduccionesRecord = Traducciones & XataRecord;

export type DatabaseSchema = {
  traducciones: TraduccionesRecord;
};

const DatabaseClient = buildClient();

const defaultOptions = {
  databaseURL: "https://Lucas-9omets.us-west-2.xata.sh/db/lata",
};

export class XataClient extends DatabaseClient<DatabaseSchema> {
  constructor(options?: BaseClientOptions) {
    super({ ...defaultOptions, ...options }, tables);
  }
}

let instance: XataClient | undefined = undefined;

export const getXataClient = () => {
  if (instance) return instance;

  instance = new XataClient();
  return instance;
};
